### ISSUE TITLE
 MOD examples don't work

### ISSUE THREAD

**Issue by patxirb** [Moddable-OpenSource/iot-product-dev-book#9] opened 2021-01-03 20:54 UTC
### Page 137-

Insufficient information to load mods examples, at least in windows 10.

So far, page 137, I have been able to get all the examples working, including "$EXAMPLES/ch3-network/host" with the msconfig command.

From now on none. Neither with mcrun nor with mcconfig. They all give error: "$EXAMPLES/ch3-network/http-get", "$EXAMPLES/ch3-network/http-get-json"...

D:\Usuarios\ni\Projects\iot-product-dev-book\ch3-network\http-get>mcrun -d -m -p esp32 ssid="WiFi-niN1" password="4es6tf8uh8"
D:\Usuarios\ni\Projects\moddable\tools\serial2xsbug\serial2xsbug_win.c(135): Se agoto el tiempo de espera del semaforo.
NMAKE : fatal error U1077: 'D:\Usuarios\ni\Projects\moddable\build\bin\win\release\serial2xsbug.EXE' : código devuelto '0x1'
Stop.

Since I have not found the solution, I can only indicate that some extra clarification is necessary.

**Comment by lprader** [comment] 2021-01-04 19:00
Hello, sorry you're having trouble!

To clarify, are you able to install the host for chapter 3? The section **Installing the Network Host** at the top of page 137 doesn't explicitly state the build command, but it's the same pattern as described in chapter 1 (that you say you were able to use):

```
cd $EXAMPLES/ch3-network/host
mcconfig -d -m -p esp
```

After you install the host, you should be able to install examples with mcrun. The build command you showed looks correct for that step.

**Comment by patxirb** [comment] 2021-01-04 20:36
Hello,

cd $EXAMPLES/ch3-network/host
mcconfig -d -m -p esp32 ssid="WifiNi" password="miPasswo0rd"

Yes, yes. All this works perfectly

![image](https://user-images.githubusercontent.com/32263158/103577123-7fdaa180-4ed4-11eb-8284-78388a402177.png)

But not this:

cd $EXAMPLES/ch3-network/http-get
mcrun -d -m -p esp32

![image](https://user-images.githubusercontent.com/32263158/103577227-b1536d00-4ed4-11eb-86fc-b755b9bb3939.png)

I translate for you:

Se agotó el tiempo del semáforo => Semaphore timed out.


All my attempts come here. I cannot advance at this point.

**Comment by lprader** [comment] 2021-01-05 00:35
The problem may be that your `UPLOAD_PORT` environment variable isn't set correctly; it should be set to the COM port for your device. 

Step 8 of our [ESP32 installation instructions](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/esp32.md#installing-1) for Windows explains how to do that, but it's described as optional for advanced users. I think it may be necessary for anyone using `mcrun`, which of course includes book readers :)

Here are the steps:

1. Plug your ESP32 into your computer
2. Launch the Windows Device Manager
3. Open the "Ports (COM & LPT)" section
4. Look for "Silicon Labs CP210x USB to UART Bridge" and note the associated COM port (e.g. `COM3`)
5. Open the "Environment Variables" dialog of the Control Panel app by following [these instructions](https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/)
6. From that dialog, create a User Variable called `UPLOAD_PORT` and set it to the COM port you noted earlier.
7. Newly-set environment variables will not take effect in existing Command Prompt instances, so be sure to open a new Command Prompt instance after applying these changes

Give that a try and let me know if it fixes the problem.

**Comment by patxirb** [comment] 2021-01-05 21:00
Looking for the solution, it is seen that I finally left the configuration wrong.

I have reinstalled everything from scratch and the symptoms have changed, but the problem persists.

During the careful reinstallation I discovered a bug in the program. In my case I have

HOMEDRIVE=D:

and

HOMEPATH=\Users\Patxi

but the installation uses

HOMEDRIVE=C:

and

HOMEPATH=\Users\Patxi

So in the variable
PATH
create the entry:

C:\user\Patxi\esp32\esp-idf\tools

Instead of:

D:\Users\Patxi\esp32\esp-idf\tools


But after making the correction the initial problem remains.

I have made a video with a concrete example. But the same thing happens with any of the MODs. Surely it is some detail that I cannot detect, but I have spent many hours trying to solve it without success.

https://user-images.githubusercontent.com/32263158/103698273-67848880-4fa1-11eb-9de9-aaf496dbc822.mp4

I really appreciate your dedication and help,

**Comment by lprader** [comment] 2021-01-06 23:10
> I really appreciate your dedication and help,

I'm happy to help! And I appreciate your patience.

The issue in the video you shared looks very different than the initial problem. The initial problem was a build error that seems to be resolved now that you've fixed your environment variables.

The issue I see in the video is that the host is not finding the mod after you install it. Since the host doesn't find the mod, it doesn't bother trying to connect to Wi-Fi (which is the expected behavior).

Can you check that your copy of this repository and the Moddable SDK are up to date?

The most recent commit in this repository should be this one:

```
lprader:iot-product-dev-book lprader$ git log
commit 99b94d6053e5c424e5335281eae298d4f690823c (HEAD -> master, origin/master, origin/HEAD)
Author: Peter Hoddie <peter@moddable.tech>
Date:   Fri Dec 18 10:04:11 2020 -0800

    convert function unnecessary now that XS handles undefined values in template literals
```

And the most recent commit in your copy of the Moddable SDK repository should be this:

```
lprader:moddable lprader$ git log
commit 86a98025fe3ea5d4c658e87c7ab9d368db60c4a8 (HEAD -> public, origin/public, origin/HEAD)
Author: Peter Hoddie <peter@moddable.tech>
Date:   Tue Jan 5 14:10:00 2021 -0800

    add mcrun, small updates
```

**Comment by patxirb** [comment] 2021-01-07 23:20
> I'm happy to help! And I appreciate your patience.

@lprader you are the winner of the courtesy duel. I've get out of words.

I had the Moddable SDK installed with commit;

`D:\Usuarios\Patxi\Projects\moddable>git log

commit 4ad0dde1b7d294b59d15a07e7660a14415ff66e5 (HEAD -> public, origin/public,origin/HEAD)
Author: Michael Kellner <mkellner@moddable.tech>
Date:   Thu Dec 31 18:16:55 2020 -0800`

I have updated it and now it is with the same one that you indicate

`D:\Usuarios\Patxi\Projects\moddable>git log
commit 86a98025fe3ea5d4c658e87c7ab9d368db60c4a8 (HEAD -> public, origin/public,origin/HEAD)
Author: Peter Hoddie <peter@moddable.tech>
Date:   Tue Jan 5 14:10:00 2021 -0800

    add mcrun, small updates`


**And now EVERYTHING works perfectly.**

I don't have words but I do have one word:

**gratefulness**

**Comment by lprader** [comment] 2021-01-08 18:36
Excellent. I'll go ahead and close this issue.

**Closed as completed by lprader** 2021-01-08 18:36 UTC
